### ISSUE TITLE
Schematic?

### ISSUE THREAD

**Issue by Alfrederson** [pscrespo/Morpheus-STM32#2]
I etched this board just because, but what program do I use to open the .sch? It's not an Eagle .sch, and Altium Designer doesn't seem to be able to import it either

**Comment by greboide** [comment]
apparently he is using gEDA suite http://www.geda-project.org/

**Comment by pscrespo** [comment]
@greboide That's correct. Current published version is made with gEDA. It's a little tricky to make it run in Windows but you can follow this guide: http://www.delorie.com/pcb/geda-windows/
I'm porting the board to KiCAD, wich is more used than gEDA these days, and is open source too.
@Alfrederson Schematic is here: https://github.com/pscrespo/Morpheus-STM32/blob/master/documents/morpheus.png
